# Generated by Django 3.0.4 on 2020-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revdigifieduser',
            name='fist_name',
            field=models.CharField(default='ignore', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revdigifieduser',
            name='last_name',
            field=models.CharField(default='these', max_length=30),
            preserve_default=False,
        ),
    ]
