# Generated by Django 3.0.4 on 2020-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_auto_20200523_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='revdigifieduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
