# Generated by Django 3.0.4 on 2020-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_revdigifieduser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revdigifieduser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
